stages:
  - build_dev
  - build_master

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375


build_dev:
  image: docker:latest
  stage: build_dev
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build 
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - dev

build_master:
  image: docker:latest
  stage: build_master
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker build -t aghozlane/shaman .
    - docker push aghozlane/shaman
  only:
    - master
