stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375


build_master:
  image: docker:latest
  stage: build
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    #- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker build -t registry-gitlab.pasteur.fr/aghozlan/shaman .
    - docker push registry-gitlab.pasteur.fr/aghozlan/shaman
    #- docker build -t aghozlane/shaman .
    #- docker push -t aghozlane/shaman