stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375


build_master:
  image: docker:latest
  stage: build
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build 
      --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"