stages:
  - build_dev
  - build_master
  - build_conda

build_dev:
  image: docker:24
  stage: build_dev
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
  only:
    - dev
    - master

build_master:
  image: docker:24
  stage: build_master
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest  -t aghozlane/shaman .
    - docker push aghozlane/shaman
  only:
    - master


build_conda:
  #image: continuumio/miniconda3:latest mutex issue
  image: conda/miniconda3-centos7:latest
  stage: build
  variables:
    CI_DEBUG_TRACE: "false"
  before_script:
    - conda config --add channels bioconda
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels aghozlane
    - conda config --set anaconda_upload yes
    - conda update conda
    - conda install -y conda-verify
    - conda install -y anaconda-client
    - conda install -y conda-build
    - conda install -y git
  script:
    - anaconda login --username "$DOCKER_USER" --password "$DOCKER_PASS"
    - conda build conda_inst
    #- res=$(conda build conda_inst --output --output-folder .)
    #- anaconda upload $res
  only:
    - tags
