stages:
  - build_conda
  - build_dev
  - build_master
  

services:
  - registry-gitlab.pasteur.fr/dsi-tools/docker-images/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375


build_dev:
  image: registry-gitlab.pasteur.fr/dsi-tools/docker-images/docker:latest
  stage: build_dev
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # - docker pull aghozlane/shaman:latest || true
    - docker build 
      --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - dev
    - master

build_master:
  image: registry-gitlab.pasteur.fr/dsi-tools/docker-images/docker:latest
  stage: build_master
  variables:
    CI_DEBUG_TRACE: "false"
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    # - docker pull aghozlane/shaman:latest || true
    - docker build -t aghozlane/shaman .
    - docker push aghozlane/shaman
  only:
    - master


build_conda:
  #image: continuumio/miniconda3:latest mutex issue
  image: conda/miniconda3-centos7:latest
  stage: build_conda
  variables:
    CI_DEBUG_TRACE: "false"
  before_script:
    - conda config --add channels bioconda
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels aghozlane
    - conda config --set anaconda_upload yes
    - conda update conda
    - conda install -y conda-verify
    - conda install -y anaconda-client
    - conda install -y conda-build
    - conda install -y git
  script:
    - anaconda login --username "$DOCKER_USER" --password "$DOCKER_PASS"
    - conda build conda_inst
    #- res=$(conda build conda_inst --output --output-folder .)
    #- anaconda upload $res
  except:
    - dev
    - master
